sonar.projectKey=phts-public-health-talent-system-backend
sonar.organization=phts-public-health-talent-system
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
sonar.architecture.configpath=architecture.yaml
