"use client"

import type { PeriodDetail, PeriodPayoutRow, PayoutDetail } from "@/features/payroll/api"

export const MOCK_UI_PERIOD_DETAIL: PeriodDetail = {
  period: {
    period_id: 9999,
    period_month: 2,
    period_year: 2026,
    status: "WAITING_HR",
    total_amount: 0,
    total_headcount: 6,
    created_at: "2026-02-15T08:00:00.000Z",
    created_by_name: "ระบบ (ตัวอย่าง)",
  },
  items: [],
  calendar: {
    total_days: 28,
    working_days: 20,
    holiday_days: 8,
    weekend_days: 8,
    public_holiday_days: 0,
  },
}

export const MOCK_UI_PAYOUT_ROWS: PeriodPayoutRow[] = [
  // 1) Eligibility starts mid-month
  {
    payout_id: 91001,
    citizen_id: "1100501215023",
    eligibility_id: 862,
    profession_code: "PHARMACIST",
    title: "นางสาว",
    first_name: "นันทิชา",
    last_name: "ตักเตือน",
    position_name: "เภสัชกร",
    department: "กลุ่มงานเภสัชกรรม",
    group_no: 1,
    item_no: "-",
    sub_item_no: "-",
    eligible_days: 17,
    deducted_days: 0,
    rate: 1500,
    retroactive_amount: 0,
    total_payable: 910.71,
    remark: "",
    check_count: 1,
    blocker_count: 0,
    warning_count: 1,
  },
  // 2) License inactive/expired (blocker)
  {
    payout_id: 91002,
    citizen_id: "1100501299999",
    eligibility_id: 863,
    profession_code: "PHARMACIST",
    title: "นาย",
    first_name: "สมชาย",
    last_name: "ใบอนุญาตหมดอายุ",
    position_name: "เภสัชกร",
    department: "กลุ่มงานเภสัชกรรม",
    group_no: 1,
    item_no: "-",
    sub_item_no: "-",
    eligible_days: 10,
    deducted_days: 0,
    rate: 1500,
    retroactive_amount: 0,
    total_payable: 535.71,
    remark: "",
    check_count: 1,
    blocker_count: 1,
    warning_count: 0,
  },
  // 3) Leave over-quota (warning)
  {
    payout_id: 91003,
    citizen_id: "1100501288888",
    eligibility_id: 864,
    profession_code: "NURSE",
    title: "นาง",
    first_name: "สายฝน",
    last_name: "ลาเกินโควตา",
    position_name: "พยาบาลวิชาชีพ",
    department: "หอผู้ป่วยใน",
    group_no: 2,
    item_no: "2.2",
    sub_item_no: "2.2.1",
    eligible_days: 24,
    deducted_days: 4,
    rate: 1500,
    retroactive_amount: 0,
    total_payable: 1285.71,
    remark: "",
    check_count: 1,
    blocker_count: 0,
    warning_count: 1,
  },
  // 4) No-pay period (blocker)
  {
    payout_id: 91004,
    citizen_id: "1100501277777",
    eligibility_id: 865,
    profession_code: "MED_TECH",
    title: "นาย",
    first_name: "ธนา",
    last_name: "ช่วงไม่รับเงินเดือน",
    position_name: "นักเทคนิคการแพทย์",
    department: "ห้องปฏิบัติการ",
    group_no: 1,
    item_no: "-",
    sub_item_no: "-",
    eligible_days: 21,
    deducted_days: 7,
    rate: 1000,
    retroactive_amount: 0,
    total_payable: 750.0,
    remark: "",
    check_count: 1,
    blocker_count: 1,
    warning_count: 0,
  },
  // 5) Retroactive add (warning)
  {
    payout_id: 91005,
    citizen_id: "1100501266666",
    eligibility_id: 866,
    profession_code: "DENTIST",
    title: "ทพ.",
    first_name: "กมล",
    last_name: "ตกเบิกเพิ่ม",
    position_name: "ทันตแพทย์",
    department: "กลุ่มงานทันตกรรม",
    group_no: 2,
    item_no: "-",
    sub_item_no: "-",
    eligible_days: 28,
    deducted_days: 0,
    rate: 7500,
    retroactive_amount: 500,
    total_payable: 8000,
    remark: "",
    check_count: 1,
    blocker_count: 0,
    warning_count: 1,
  },
  // 6) Retroactive deduct (warning)
  {
    payout_id: 91006,
    citizen_id: "1100501255555",
    eligibility_id: 867,
    profession_code: "PHYSIO",
    title: "นางสาว",
    first_name: "ศิริพร",
    last_name: "ตกเบิกหัก",
    position_name: "นักกายภาพบำบัด",
    department: "เวชกรรมฟื้นฟู",
    group_no: 5,
    item_no: "-",
    sub_item_no: "-",
    eligible_days: 28,
    deducted_days: 0,
    rate: 1000,
    retroactive_amount: -300,
    total_payable: 700,
    remark: "",
    check_count: 1,
    blocker_count: 0,
    warning_count: 1,
  },
]

export const MOCK_UI_PAYOUT_DETAILS: Record<number, PayoutDetail> = {
  91001: {
    payout: {
      payout_id: 91001,
      period_id: 9999,
      period_month: 2,
      period_year: 2026,
      citizen_id: "1100501215023",
      profession_code: "PHARMACIST",
      group_no: 1,
      pts_rate_snapshot: 1500,
      calculated_amount: 910.71,
      retroactive_amount: 0,
      total_payable: 910.71,
      eligible_days: 17,
      deducted_days: 0,
      remark: "",
      title: "นางสาว",
      first_name: "นันทิชา",
      last_name: "ตักเตือน",
      position_name: "เภสัชกร",
      department: "กลุ่มงานเภสัชกรรม",
    },
    items: [
      {
        item_id: 1,
        payout_id: 91001,
        reference_month: 2,
        reference_year: 2026,
        item_type: "CURRENT",
        amount: 910.71,
        description: "ค่าตอบแทนงวดปัจจุบัน",
      },
    ],
    checks: [
      {
        check_id: 1,
        payout_id: 91001,
        code: "ELIGIBILITY_GAP",
        severity: "WARNING",
        title: "สิทธิเริ่มมีผลกลางเดือน / สิทธิไม่ครอบคลุมทั้งงวด",
        summary:
          "กระทบ 11 วัน • ประมาณ -589.29 บาท • ไม่มีสิทธิ 2026-02-01 ถึง 2026-02-11",
        evidence: [
          {
            type: "eligibility",
            rate: 1500,
            rate_id: 98,
            effective_date: "2026-02-12",
            expiry_date: null,
          },
          {
            type: "eligibility_gap",
            work_start_date: "2026-02-01",
            work_end_date: "2026-02-28",
            missing_ranges: [{ start: "2026-02-01", end: "2026-02-11" }],
          },
        ],
      },
    ],
  },
  91002: {
    payout: {
      payout_id: 91002,
      period_id: 9999,
      period_month: 2,
      period_year: 2026,
      citizen_id: "1100501299999",
      profession_code: "PHARMACIST",
      group_no: 1,
      pts_rate_snapshot: 1500,
      calculated_amount: 535.71,
      retroactive_amount: 0,
      total_payable: 535.71,
      eligible_days: 10,
      deducted_days: 0,
      remark: "",
      title: "นาย",
      first_name: "สมชาย",
      last_name: "ใบอนุญาตหมดอายุ",
      position_name: "เภสัชกร",
      department: "กลุ่มงานเภสัชกรรม",
    },
    items: [
      {
        item_id: 1,
        payout_id: 91002,
        reference_month: 2,
        reference_year: 2026,
        item_type: "CURRENT",
        amount: 535.71,
        description: "ค่าตอบแทนงวดปัจจุบัน",
      },
    ],
    checks: [
      {
        check_id: 1,
        payout_id: 91002,
        code: "NO_LICENSE",
        severity: "BLOCKER",
        title: "ใบอนุญาตไม่ ACTIVE บางช่วง",
        summary:
          "กระทบ 18 วัน • ประมาณ -964.29 บาท • ไม่มีสิทธิ 2026-02-11 ถึง 2026-02-28",
        evidence: [
          {
            type: "license",
            status: "EXPIRED",
            valid_from: "2021-05-14",
            valid_until: "2026-02-10",
          },
        ],
      },
    ],
  },
  91003: {
    payout: {
      payout_id: 91003,
      period_id: 9999,
      period_month: 2,
      period_year: 2026,
      citizen_id: "1100501288888",
      profession_code: "NURSE",
      group_no: 2,
      pts_rate_snapshot: 1500,
      calculated_amount: 1285.71,
      retroactive_amount: 0,
      total_payable: 1285.71,
      eligible_days: 24,
      deducted_days: 4,
      remark: "",
      title: "นาง",
      first_name: "สายฝน",
      last_name: "ลาเกินโควตา",
      position_name: "พยาบาลวิชาชีพ",
      department: "หอผู้ป่วยใน",
    },
    items: [
      {
        item_id: 1,
        payout_id: 91003,
        reference_month: 2,
        reference_year: 2026,
        item_type: "CURRENT",
        amount: 1285.71,
        description: "ค่าตอบแทนงวดปัจจุบัน",
      },
    ],
    checks: [
      {
        check_id: 1,
        payout_id: 91003,
        code: "OVER_QUOTA",
        severity: "WARNING",
        title: "ลาเกินโควต้า",
        summary: "กระทบ 4 วัน • ประมาณ -214.29 บาท • 2026-02-18 ถึง 2026-02-21",
        evidence: [
          {
            type: "leave",
            leave_record_id: 12345,
            leave_type: "sick",
            start_date: "2026-02-18",
            end_date: "2026-02-21",
            is_no_pay: false,
            over_quota: true,
            exceed_date: "2026-02-18",
            quota_limit: 60,
            leave_duration: 4,
            quota_unit: "business_days",
          },
        ],
      },
    ],
  },
  91004: {
    payout: {
      payout_id: 91004,
      period_id: 9999,
      period_month: 2,
      period_year: 2026,
      citizen_id: "1100501277777",
      profession_code: "MED_TECH",
      group_no: 1,
      pts_rate_snapshot: 1000,
      calculated_amount: 750,
      retroactive_amount: 0,
      total_payable: 750,
      eligible_days: 21,
      deducted_days: 7,
      remark: "",
      title: "นาย",
      first_name: "ธนา",
      last_name: "ช่วงไม่รับเงินเดือน",
      position_name: "นักเทคนิคการแพทย์",
      department: "ห้องปฏิบัติการ",
    },
    items: [
      {
        item_id: 1,
        payout_id: 91004,
        reference_month: 2,
        reference_year: 2026,
        item_type: "CURRENT",
        amount: 750,
        description: "ค่าตอบแทนงวดปัจจุบัน",
      },
    ],
    checks: [
      {
        check_id: 1,
        payout_id: 91004,
        code: "NO_PAY",
        severity: "BLOCKER",
        title: "ช่วง no-pay (ไม่รับเงินเดือน)",
        summary: "กระทบ 7 วัน • ประมาณ -250 บาท • 2026-02-03 ถึง 2026-02-09",
        evidence: [
          {
            type: "leave",
            leave_record_id: 67890,
            leave_type: "education",
            start_date: "2026-02-03",
            end_date: "2026-02-09",
            is_no_pay: true,
            over_quota: false,
            exceed_date: null,
          },
        ],
      },
    ],
  },
  91005: {
    payout: {
      payout_id: 91005,
      period_id: 9999,
      period_month: 2,
      period_year: 2026,
      citizen_id: "1100501266666",
      profession_code: "DENTIST",
      group_no: 2,
      pts_rate_snapshot: 7500,
      calculated_amount: 7500,
      retroactive_amount: 500,
      total_payable: 8000,
      eligible_days: 28,
      deducted_days: 0,
      remark: "",
      title: "ทพ.",
      first_name: "กมล",
      last_name: "ตกเบิกเพิ่ม",
      position_name: "ทันตแพทย์",
      department: "กลุ่มงานทันตกรรม",
    },
    items: [
      {
        item_id: 1,
        payout_id: 91005,
        reference_month: 2,
        reference_year: 2026,
        item_type: "CURRENT",
        amount: 7500,
        description: "ค่าตอบแทนงวดปัจจุบัน",
      },
      {
        item_id: 2,
        payout_id: 91005,
        reference_month: 1,
        reference_year: 2026,
        item_type: "RETROACTIVE_ADD",
        amount: 500,
        description: "ตกเบิกย้อนหลัง (เพิ่ม)",
      },
    ],
    checks: [
      {
        check_id: 1,
        payout_id: 91005,
        code: "RETRO_ADD",
        severity: "WARNING",
        title: "ตกเบิกย้อนหลัง (เพิ่ม)",
        summary: "อ้างอิง 1/2026 • +500 บาท",
        evidence: [
          {
            type: "retro",
            reference_month: 1,
            reference_year: 2026,
            diff: 500,
            remark: "ปรับเรทย้อนหลังหลังอนุมัติ",
          },
        ],
      },
    ],
  },
  91006: {
    payout: {
      payout_id: 91006,
      period_id: 9999,
      period_month: 2,
      period_year: 2026,
      citizen_id: "1100501255555",
      profession_code: "PHYSIO",
      group_no: 5,
      pts_rate_snapshot: 1000,
      calculated_amount: 1000,
      retroactive_amount: -300,
      total_payable: 700,
      eligible_days: 28,
      deducted_days: 0,
      remark: "",
      title: "นางสาว",
      first_name: "ศิริพร",
      last_name: "ตกเบิกหัก",
      position_name: "นักกายภาพบำบัด",
      department: "เวชกรรมฟื้นฟู",
    },
    items: [
      {
        item_id: 1,
        payout_id: 91006,
        reference_month: 2,
        reference_year: 2026,
        item_type: "CURRENT",
        amount: 1000,
        description: "ค่าตอบแทนงวดปัจจุบัน",
      },
      {
        item_id: 2,
        payout_id: 91006,
        reference_month: 12,
        reference_year: 2025,
        item_type: "RETROACTIVE_DEDUCT",
        amount: 300,
        description: "ตกเบิกย้อนหลัง (หัก)",
      },
    ],
    checks: [
      {
        check_id: 1,
        payout_id: 91006,
        code: "RETRO_DEDUCT",
        severity: "WARNING",
        title: "ตกเบิกย้อนหลัง (หัก)",
        summary: "อ้างอิง 12/2025 • -300 บาท",
        evidence: [
          {
            type: "retro",
            reference_month: 12,
            reference_year: 2025,
            diff: -300,
            remark: "แก้ไขข้อมูลย้อนหลัง ทำให้ต้องคืนเงิน",
          },
        ],
      },
    ],
  },
}
